// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCQXWbfp9hEaiyh8J8JMlKONW-_qSe6BI',
    appId: '1:480819346188:web:0569db6f67d62ea582a729',
    messagingSenderId: '480819346188',
    projectId: 'speakwithme-535f1',
    authDomain: 'speakwithme-535f1.firebaseapp.com',
    storageBucket: 'speakwithme-535f1.appspot.com',
    measurementId: 'G-07TS6WJP3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxQK0Djylrk4nyCU20T_CxND8zQj2hqtE',
    appId: '1:480819346188:android:f269b5575144a80f82a729',
    messagingSenderId: '480819346188',
    projectId: 'speakwithme-535f1',
    storageBucket: 'speakwithme-535f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuxgo387_a629jHyWxlNFZeD8cNvoEXcw',
    appId: '1:480819346188:ios:f504bac61a2de51482a729',
    messagingSenderId: '480819346188',
    projectId: 'speakwithme-535f1',
    storageBucket: 'speakwithme-535f1.appspot.com',
    androidClientId: '480819346188-9bg9hk6kba54hbc0a97stju5d19abm5b.apps.googleusercontent.com',
    iosClientId: '480819346188-l0rfktou5228ueo12ea25hud8es25mg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.speakwithmeAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuxgo387_a629jHyWxlNFZeD8cNvoEXcw',
    appId: '1:480819346188:ios:d8e5dcb64b49a13b82a729',
    messagingSenderId: '480819346188',
    projectId: 'speakwithme-535f1',
    storageBucket: 'speakwithme-535f1.appspot.com',
    androidClientId: '480819346188-9bg9hk6kba54hbc0a97stju5d19abm5b.apps.googleusercontent.com',
    iosClientId: '480819346188-ukvo4dj8mp420r752280nb9nu6876j7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.speakwithmeAi.RunnerTests',
  );
}
